[server]
host="localhost"
port="9000"
useHttps=false
https_port="9001"
pemPath=""
keyPath=""

[mysql]
host="localhost" #gDSN = "root:123456@tcp(localhost:3306)/mall?charset=utf8&parseTime=True&loc=Local"
port="3306"
mysql_username="root"
mysql_password="123456"



